services:
  - type: web
    name: fraud-ml-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.fraudml.api.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
    region: oregon
