global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  - job_name: 'fraud-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['fraud-api:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+):\\d+'
        replacement: '${1}'

  - job_name: 'redis'
    static_configs:
      - targets: ['fraud-redis:6379']

  - job_name: 'postgres'
    static_configs:
      - targets: ['fraud-db:5432']
